[build]
  publish = "."
  command = ""

# PWA headers básicos
[[headers]]
  for = "/sw.js"
  [headers.values]
  Cache-Control = "no-cache"

# Não reescrever nada dentro de /app/*
[[redirects]]
  from = "/app/*"
  to = "/app/:splat"
  status = 200

# SPA fallback apenas para o portal raiz
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200