name: Deploy to Firebase Hosting

on:
  push:
    branches: [ portal ]   # troque para main se quiser

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy Hosting
        run: firebase deploy --only hosting --project unikorapp
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
